version: 0.2

env:
  parameter-store:
    PARAM: "CodeBuild/PARAM"
  secrets-manager:
    SECRET: test-ninja:SECRET

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
    - echo ///// $DEPLOY_ENV //////
    - echo dependencies
    - npm install -g browserify
    - npm install -g plato
    - npm install
    - npm audit fix --force
    - mkdir dist
    - cp -Rf src/public/* dist/
    - echo "PARAM="${PARAM} >> .env
    - echo "SECRET="${SECRET} >> .env
    - echo "NODE_ENV="${$DEPLOY_ENV} >> .env
  pre_build:
    commands:
    - echo Test starts
    - npm run test
    - echo Test ends
    - echo Quality check starts
    - npm run quality
    - echo Quality check ends
  build:
    commands:
    - npm run build
  post_build:
    commands:
    - echo Deploy started on `date`
    - npm run deploy:$DEPLOY_ENV
    - echo Build completed on `date`
